### ISSUE TITLE
remove fabric dependency

### ISSUE THREAD

**Issue by evansde77** [evansde77/cirrus#135]
Looks like fabric isnt python3 compatible, and its dependencies cause repeated problems. 
For the fairly simple operations we use it for in cirrus, we should be able to replace it:
- Several uses of local() to execute shell commands - replace these with subprocess calls
- Remote file copies in plugins
  - Option1: dynamic import of fabric in the plugin - ugh 
  - Option2: refactor to run an scp command via subprocess
  - Option3: refactor to use paramiko 
- deploy command
  - Dont think anyone is using this, but it can be easily dropped to a dynamic import in a first pass

@appeltel @shudgston any potential issues with this?

**Comment by appeltel** [comment]
I'd be very happy to move away from fabric, use subprocess for the local commands.

Options 2 or 3 sound reasonable. I can't think of any issues this would cause at the moment.

**Comment by evansde77** [comment]
Switching to invoke for local commands, only fabric remote stuff is using put and have a simple scp wrapper for that.
