### ISSUE TITLE
git cirrus build does not preserve file permissions

### ISSUE THREAD

**Issue by jordansamuels** [evansde77/cirrus#197]
When copying files from e.g. `container-template` to `image-dir`, the command `git cirrus build` will change permissions.  This prevents us from doing things cleanly in `Dockerfile.mustache` like:

```
COPY my_script.sh /usr/local/bin
```

because `my_script.sh` will lose executable permissions.  The workaround is either to use post script or just use:

```
COPY my_script.sh /usr/local/bin
RUN chmod +x /usr/loca/bin/my_script.sh
```

**Comment by evansde77** [comment]
Tweaked dockerstache to preserve permissions, fix added to https://github.com/evansde77/cirrus/tree/feature/fix-docker-image-output

**Comment by jordansamuels** [comment]
Fix seems good, thanks.
