### ISSUE TITLE
Fresh install with conda has error?

### ISSUE THREAD

**Issue by jordansamuels** [evansde77/cirrus#202]
Using conda 4.4.10 or 4.5.1, I can run `conda-installer.sh` and it will install, however it does have this error:

```
conda-installer.sh: line 36: /Users/jordan/.cirrus/venv/bin/activate: No such file or directory
```
This probably affects negatively the behavior of the lines in the script after that.  I didn't need them, but I figure it's good to report anyway.

**Comment by evansde77** [comment]
Fixed and pushed to head on develop
