### ISSUE TITLE
non-existent docker directory makes "cirrus docker-image build"  build fail 

### ISSUE THREAD

**Issue by jordansamuels** [evansde77/cirrus#204]
The `git cirrus docker-image build` command want to put artifacts into the `[docker] directory` dir, but this dir doesn't exist, so it fails (unless one does e.g. `mkdir -p image-dir` first).

The `docker-image build` command could do the equivalent of `mkdir -p` (maybe `os.makedirs(exist_ok=True)` if we are in Python 3) each time; or we could maybe have `git cirrus package container-init` create the directory?  The former is arguable more robust.

**Comment by evansde77** [comment]
Added a check to make the image-dir if it doesnt exist in the docker-build command
