### ISSUE TITLE
Document the installer's expectations

### ISSUE THREAD

**Issue by ksnavely** [evansde77/cirrus#38]
It expects you to have virtualenv and pip etc...standard python helpers.

This is likely on a user's machine but perhaps not on config-management controlled infra. We can test for these dependencies and exit 1 with logging if they are missing, as well as expand the install guide.

**Comment by evansde77** [comment]
Most of this addressed by the refactor of installers to use pip, will add section to package readme and close this out.

**Comment by evansde77** [comment]
Readme update is done.
