### ISSUE TITLE
Update dependencies in venv as part of selfupdate command

### ISSUE THREAD

**Issue by evansde77** [evansde77/cirrus#98]
Need this if the dependencies update but the venv doesnt. 

Ideally something like:
git cirrus selfupdate --dependencies 
would do a pip install --upgrade on the cirrus venv

Would offset issues like https://github.com/evansde77/cirrus/pull/97

**Comment by ksnavely** [comment]
I would recommend creating a fresh venv for each upgrade as well.

**Comment by evansde77** [comment]
Yeah, I guess just wiping and reinstalling would be good.

**Comment by evansde77** [comment]
Actually looks like we can just run this in the venv to update: pip install --upgrade  -r requirements.txt
A little bit less existential crisis than deleting and rebuilding the venv we are running from.

**Comment by evansde77** [comment]
Added an --upgrade option to build and made selfupdate call that when it runs, which gets new dependencies 
See: https://github.com/evansde77/cirrus/pull/101
